### ISSUE TITLE
Unas sugerencias

### ISSUE THREAD

**Issue by benchi99** [cahema/Compilador-SMR2#1]
Si no te importa que te haga alguna que otra sugerencia, (y si te importa, te jodes, ya he escrito el issue, jA), yo haría las siguientes cosas:

- Utiliza JQuery a excepción de que se esté terminantemente prohibido utilizar librerías externas.
- Los comentarios son extensos y eso está cojonudo, pero los comentarios de función podrías hacerlos que fueran como documentación. (Y así además si utilizas después una herramienta de generado de documentación así pa nota y tal, que puede que no, pero bueno). Por ejemplo:

Lo que tu tienes
```
/*
* Ejecutar
*
*	Esta función interpreta y ejecuta la serie de números binarios en el
*	textarea de binario y muestra el output que generaría ese código
*
*/

function ejecutar() {

	let txtBinario      = document.querySelector("#txtBinario").value;
	let divErrorBinario = document.querySelector("#divErrorBinario");
        ...
```

Como yo lo haría
```
/**
 * @name Ejecutar
 * 
 * Esta función interpreta y ejecuta la serie de numeros binarios
 * en el textarea de binario y muestra el output que generaría ese código
 *
 */

function ejecutar() {

	let txtBinario      = document.querySelector("#txtBinario").value;
	let divErrorBinario = document.querySelector("#divErrorBinario");
        ...
```
(Y así en IDEs como Visual Studio Code, te muestra lo que hace la función)
![image](https://user-images.githubusercontent.com/29159617/74933856-3a5cd500-53e5-11ea-8f89-137458363d2b.png)

Espero que estas sugerencias te sirvan de algo. Un saludo del tito bencho y buena suerte, tienes un proyectazo aquí

**Comment by cahema** [comment]
Estoy de acuerdo en que debo mejorar los comentarios pero por el momento estoy trabajando en reestructurar el código para dejarlo más a mi gusto
El proyecto tiene que ser exclusivamente en Javascript
